name: Swoppy
description: A new Flutter application to match business partners.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  camera: ^0.5.8+2
  path_provider: ^1.6.11
  path:
  cupertino_icons: ^0.1.3
  firebase_core: ^0.4.5
  firebase_auth: ^0.16.1
  cloud_firestore: ^0.13.7
  google_sign_in: ^4.5.1
  rxdart: ^0.24.1
  grouped_buttons: ^1.0.4
  modal_progress_hud: ^0.1.3
  font_awesome_flutter: ^8.8.1
  fluttertoast: ^4.0.1
  video_player: ^0.10.11+2
  esys_flutter_share: ^1.0.2
  video_thumbnail: ^0.2.2
  flutter_form_builder: ^3.11.5
  flutter_radar_chart: ^0.1.3
  firebase_storage: ^3.1.6
  flutter_swiper: ^1.1.6
  flutter_page_indicator:
  auto_size_text: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - images/

  fonts:
    - family: Open Sans
      fonts:
        - asset: fonts/OpenSans-Light.ttf
        - asset: fonts/OpenSans-Regular.ttf
        - asset: fonts/OpenSans-SemiBold.ttf
